[package]
name = "nexus-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nexus-core = {workspace = true}
pingora = {workspace = true}
trie-hard = "0.1.0"
async-trait = "0.1.88"