[package]
name = "nexus-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "nexus_core"
path = "src/lib.rs"

[dependencies]
pingora = { workspace = true }
async-trait = "0.1.88"
trie-hard = "0.1.0"
tokio = { version = "1.44.1", features = ["fs"] }
arc-swap = "1.7.1"
serde = "1.0.219"
serde_json = "1.0.140"
dashmap = "6.1.0"
bytes = "1.10.1"
once_cell = { version = "1.21.1" }
ctor = "0.4.1"
matchit = "0.8.6"